apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offers
  template:
    metadata:
      labels:
        app: offers
    spec:
      containers:
      - name: offers
        image: offerzone-offers:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: PORT
          value: "8002"
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_URI_OFFERS
---
apiVersion: v1
kind: Service
metadata:
  name: offers
spec:
  selector:
    app: offers
  ports:
  - name: http
    port: 8002
    targetPort: 8002
